### ISSUE TITLE
0.2.1 release

### ISSUE THREAD

**Issue by est31** [qnighy/yasna.rs#29]
@jethrogb do you have any further changes left to upstream? If not, I'd like to make a 0.2.1 release.

**Comment by jethrogb** [comment]
Yes I have one more PR coming. But you can do a point release now if you want.

**Comment by est31** [comment]
I guess I'll wait for your PR :). Right now the PR rate is quite high (11 PRs in the last week), but I expect it to get less in the coming weeks and months (unless you have different plans ofc :p). The goal of the release is to avoid a situation where there are a couple of commits on master but there is no release for a long time so crates.io users will have to continue to use an outdated version.

**Comment by jethrogb** [comment]
cc @mzohreva
